apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitochron
spec:
  selector:
    matchLabels:
      app: mitochron
  replicas: 2
  template:
    metadata:
      labels:
        app: mitochron
    spec:
      containers:
      - name: mitochron
        image: dredgreat/mitochron:latest
        ports:
          - containerPort: 3001
        env:
          - name: MONGODB_URI
            value: mongodb+srv://plum:plum@cluster0.sw2l8.mongodb.net/mitochron-production?retryWrites=true&w=majority
          - name: APP_NAME
            value: Mitochron
          - name: JWT_KEY
            value: mitochron_secret_key
          - name: CLIENT_URL
            value: http://localhost
          - name: PORT
            value: '3001'
          - name: JWT_EXPIRES_AT
            value: 90d
          - name: BCRYPT_SALT_ROUNDS
            value: '10'
          

        imagePullPolicy: Always
